apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fe05
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-fe05@sha256:6f5fecf8dcd8619ca86a490cf36982e99c36d583e07dde269b0e5bb9b060e991
        name: my-nodejs
        resources: {}
status: {}
